[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "safe-bit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "cryptography",
]

[dependency-groups]
dev = [
  "pytest>=8",
]

[tool.hatch.build.targets.wheel]
packages = ["src/safe_bit"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.pyright]
extraPaths = ["src"]
venvPath = ".devenv/state"
venv = "venv"

[tool.ruff]
target-version = "py314"
